# Usage: prospector >  prospector_report.json

output-format: json

strictness: low

test-warnings: true
doc-warnings: false
member-warnings: true

ignore-paths:
  - docs
  - build
  - crawler/tests

pylint:
  disable:
    - line-too-long

dodgy:
  run: false

pep257:
  disable:
    - D204
    - D213
    - D107
    - D203

pep8:
  run: false
  full: true
  disable:
    # indentation contains tabs:
    - W191

# pip install prospector[with_pyroma]
pyroma:
  run: true

# pip install prospector[with_vulture]
# vulture:
#   run: true

pyflakes:
  run: false
