# Usage: prospector >>  prospector_report.json

output-format: json

strictness: low

test-warnings: true
doc-warnings: false
member-warnings: true

ignore-paths:
  - docs

pylint:
  disable:
    - line-too-long

dodgy:
  disable:
    - password

pep257:
  disable:
    - D204
    - D213
    - D107
    - D203

pep8:
  full: true
  disable:
    # indentation contains tabs:
    - W191

# pip install prospector[with_pyroma]
pyroma:
  run: true
