language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
before_script:
  - "export PYTHONPATH=crawler"
branches:
  only:
    - master
    - develop
script:
  - "coverage run setup.py test"
after_success:
  - coveralls
