language: python
python:
  - "3.4"
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install pytest pytest-cov"
    - "pip install coveralls"
# cd to crawler folder
before_script: cd crawler
# command to run tests
branches:
  only:
    - master
    - develop
script:
    - "PYTHONPATH=. py.test"

after_success: 
    - coveralls
